
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

template:
    - sensor: !include_dir_merge_list sensor/

system_log:
  max_entries: 3650
  
logger:
  default: info